name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    name: Web Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate

      - name: Install dependencies (workspace)
        run: pnpm install -w

      - name: Lint
        working-directory: apps/web
        run: pnpm lint

      - name: Build
        working-directory: apps/web
        run: pnpm build
