name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    name: Web Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: true
          

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install dependencies (web)
        working-directory: apps/web
        run: pnpm install

      - name: Lint
        working-directory: apps/web
        run: pnpm lint

      - name: Build
        working-directory: apps/web
        run: pnpm build
