name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    name: Web Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # No version here; use package.json's packageManager

      - name: Install dependencies (root)
        run: pnpm install --no-frozen-lockfile

      - name: Lint (turbo)
        run: pnpm dlx turbo run lint --filter=web

      - name: Build (turbo)
        run: pnpm dlx turbo run build --filter=web
